<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFrameworks>net10.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Desert.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Desert.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.10.4" />
    <PackageReference Include="MSTest.TestFramework" Version="3.10.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenXMLSDK.Engine\OpenXMLSDK.Engine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
